### ISSUE TITLE
패키지 발전을 위해 도움을 요청드립니다.

### ISSUE THREAD

**Issue by mym0404** [mym0404/react-native-naver-map#1]
>[!NOTE]
>New/Old Architecture 자유롭게 구동해주시면 됩니다.

---

직접 써보시거나 이 프로젝트를 클론해 `example` 앱을 사용해보시면서 버그 리포트, 기능 요청을 해주시면 감사하겠습니다. (이 이슈의 댓글로 남겨주셔도 좋습니다.)

---

We would appreciate it if you could try this version yourself or clone this project and use the `example` app and submit bug reports or feature requests. (You can also leave a comment on this issue.)

---

- [Example App Guide](https://github.com/mj-studio-library/react-native-naver-map/blob/main/CONTRIBUTING.md#development-workflow)
- [Package Usage](https://github.com/mj-studio-library/react-native-naver-map#usage)

**Comment by dioqio** [comment]
android에서만 발생합니다.
1. screenToCoordinate 함수에서 longitude, latitude 반대로 전달 됩니다.
2. setLocationTrackingMode 작동하지 않습니다.
