### ISSUE TITLE
[BUG]: Can't build on Android

### ISSUE THREAD

**Issue by nhatnguyen95** [mym0404/react-native-naver-map#104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of @mj-studio/react-native-naver-map

1.5.9

### Version of react-native

0.75.2

### What os are you seeing the problem on?

Android

### What device types are you seeing the problem on?

Simulator, Physcial Device

### What architecture types of react native are you seeing the problem on?

Old Architecture(Bridge)

### Version of device(android API, iOS OS version, etc...)

Android 34

### Expo App

- [ ] I am using Expo

### What happened?

I am staying Vietnam, I have added in build.gradle as below
`
maven {
            url "https://repository.map.naver.com/archive/maven"
        }
`
 But it give an error when building gradle
![image](https://github.com/user-attachments/assets/5c111896-8d9f-4907-9ecf-2d60a74f079f)

NOTE: My current project can't work with new arch

### Relevant a package.json.

```json
{
  "name": "ecommerce",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.23.1",
    "@react-navigation/native": "^6.1.15",
    "@react-navigation/native-stack": "^6.9.23",
    "@reduxjs/toolkit": "^2.2.6",
    "react": "18.3.1",
    "react-native": "0.75.2",
    "react-native-paper": "^5.12.3",
    "react-native-safe-area-context": "^4.9.0",
    "react-native-screens": "^3.29.0",
    "react-native-vector-icons": "^10.1.0",
    "react-redux": "^9.1.2",
    "redux-persist": "^6.0.0",
    "@mj-studio/react-native-naver-map": "^1.5.9"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native/babel-preset": "0.75.2",
    "@react-native/eslint-config": "0.75.2",
    "@react-native/metro-config": "0.75.2",
    "@react-native/typescript-config": "0.75.2",
    "@types/jest": "^29.5.12",
    "@types/react": "^18.2.6",
    "@types/react-native-vector-icons": "^6.4.18",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.6.3",
    "eslint": "^8.19.0",
    "jest": "^29.6.3",
    "prettier": "2.8.8",
    "react-test-renderer": "18.3.1",
    "typescript": "5.0.4"
  },
  "engines": {
    "node": ">=18"
  }
}
```

### Relevant log output

```shell
Could not determine the dependencies of task ':app:processDebugResources'.
> Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.naver.maps:map-sdk:3.18.0.
     Searched in the following locations:
       - https://oss.sonatype.org/content/repositories/snapshots/com/naver/maps/map-sdk/3.18.0/map-sdk-3.18.0.pom
       - https://repo.maven.apache.org/maven2/com/naver/maps/map-sdk/3.18.0/map-sdk-3.18.0.pom
       - file:/Users/nhatnguyen95/Data/Workspaces/ecommerce/node_modules/jsc-android/dist/com/naver/maps/map-sdk/3.18.0/map-sdk-3.18.0.pom
       - https://dl.google.com/dl/android/maven2/com/naver/maps/map-sdk/3.18.0/map-sdk-3.18.0.pom
       - https://www.jitpack.io/com/naver/maps/map-sdk/3.18.0/map-sdk-3.18.0.pom
     Required by:
         project :app > project :mj-studio_react-native-naver-map

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

### Reproducible Sample Repository

https://github.com/nhatnguyen95/ecommerce-app

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BangDori** [comment]
@nhatnguyen95 hello, I hope this comment helps!

The buildscript block is primarily used to define plugins and dependencies required to build the Gradle build script itself, so dependencies like the Naver Maps SDK should be defined in the allprojects block as follows.

```gradle
buildscript {
    ext {
        buildToolsVersion = "34.0.0"
        minSdkVersion = 23
        compileSdkVersion = 34
        targetSdkVersion = 34
        ndkVersion = "26.1.10909125"
        kotlinVersion = "1.9.24"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin")
    }
}

allprojects {
    repositories {
        maven {
            url "https://repository.map.naver.com/archive/maven"
        }
    }
}

apply plugin: "com.facebook.react.rootproject"
```

**Comment by nhatnguyen95** [comment]
@BangDori it's give me another error
![image](https://github.com/user-attachments/assets/94a721bf-0f6c-49f0-b8ff-1330fec947c8)

**Comment by BangDori** [comment]
@nhatnguyen95 

Could you show all the log records related to the failures?

**Comment by nhatnguyen95** [comment]
![image](https://github.com/user-attachments/assets/21dc43db-687a-4b7d-b76e-8ae72bbdf1cb)
@BangDori it shows as above, I have updated the code have errors in https://github.com/nhatnguyen95/ecommerce-app . Could you help me to check it?

**Comment by BangDori** [comment]
@nhatnguyen95 

<div align="center">
<img src="https://github.com/user-attachments/assets/76257dc2-4acb-4727-91e8-444cb511460e" width="480" />
</div>

```kotlin
// RNCNaverMapViewManager.kt

- override fun addView(
+ fun addView(
  parent: RNCNaverMapViewWrapper?,
  child: View,
  index: Int,
) {
  parent?.withMapView {
    it.addOverlay(child, index)
  }
}

override fun getChildCount(parent: RNCNaverMapViewWrapper): Int {
  return parent.mapView?.overlays?.size ?: 0
}

- override fun getChildAt(
+ fun getChildAt(
  parent: RNCNaverMapViewWrapper?,
  index: Int,
): View? {
  return parent?.mapView?.overlays?.get(index)
}

- override fun removeViewAt(
+ fun removeViewAt(
  parent: RNCNaverMapViewWrapper?,
  index: Int,
) {
  parent?.withMapView {
    it.removeOverlay(index)
  }
}

// RNCNaverMapMarkerManager.kt

- override fun addView(
+ fun addView(
  parent: RNCNaverMapMarker?,
  child: View,
  index: Int,
) {
  parent?.setCustomView(child, index)
}

- override fun removeViewAt(
+ fun removeViewAt(
  parent: RNCNaverMapMarker?,
  index: Int,
) {
  parent?.removeCustomView(index)
}
```

I built it in Android Studio and moved to the point where the error occurred, then removed the `override` as in the code above and successfully built it. However, it doesn't seem like the correct solution... just quick fix.  T. T 😭

Well, I think the error currently occurring is related to React Native v0.75.2. After checking issues with other libraries, I found that the same error occurs in v0.75.2 as well react-native-pager-view [#850](https://github.com/callstack/react-native-pager-view/issues/850), [#862](https://github.com/callstack/react-native-pager-view/issues/862).

In my opinion, the only solutions would be to either downgrade the React Native version to v0.74.x or update the @mj-studio/react-native-naver-map package to the latest version. - #96, #97, #100

**Comment by mym0404** [comment]
Android `View` method signatures has been changed from `0.75`. I did fix for `1.x` also. Try `1.5.10`.
