### ISSUE TITLE
겹침 마커 처리 구현은 어떻게 하나요?

### ISSUE THREAD

**Issue by seehun** [mym0404/react-native-naver-map#33]
해당 라이브러리를 활용해 서비스를 만들고 있는데, readme의 gif파일에 보이는 기능을 구현하고자 합니다.
마커들을 포괄하는 상위의 마커를 두고, 하위에 몇개의 마커가 있는지 숫자로 표시하는 기능을 이 라이브러리로 어떻게 구현할 수 있는건가요?

**Comment by mym0404** [comment]
[clusters](https://mym0404.github.io/react-native-naver-map/interfaces/NaverMapViewProps.html#clusters) prop을 쓰시면 됩니다.

**Comment by seehun** [comment]
감사합니다ㅠ
