### ISSUE TITLE
[BUG]: Error setting property 'clusters' of RNCNaverMapView

### ISSUE THREAD

**Issue by Arthur-Noh** [mym0404/react-native-naver-map#44]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of @mj-studio/react-native-naver-map

1.5.7

### Version of react-native

0.71.19

### What os are you seeing the problem on?

iOS

### What device types are you seeing the problem on?

Physcial Device

### What architecture types of react native are you seeing the problem on?

Old Architecture(Bridge)

### Version of device(android API, iOS OS version, etc...)

iOS 12.4

### Expo App

- [ ] I am using Expo

### What happened?

안녕하세요. 개발자님.
귀하의 패키지 노고에 감사드립니다.

라이브러리를 RN 0.71.1 버전에서 설치하면 아이폰 빌드는 성공하지만, 구동시 오류가 발생합니다.
Xcode 로그를 보면 다음과 같은 오류가 발생합니다.
오류가 발생한 기기 및 Xcode 이미지를 같이 첨부합니다.

[Xcode 로그 이미지](https://github.com/mym0404/react-native-naver-map/assets/88483892/45fbd262-fb21-4058-9704-64a15a5fd717)
[실물 기기 오류 이미지](https://github.com/mym0404/react-native-naver-map/assets/88483892/6b954f75-bcba-4cf6-bea6-822e7bb92e63)

재현 가능한 프로젝트를 제 리포지토리에 남깁니다.
검토해주시면 감사하겠습니다.

https://github.com/Arthur-Noh/nmapSample

### Relevant a package.json.

```json
{
  "name": "mapSample",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "watchman watch-del-all && react-native start --reset-cache",
    "adb": "adb reverse tcp:8081 tcp:8081",
    "android": "react-native run-android --active-arch-only",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "test": "jest"
  },
  "dependencies": {
    "@mj-studio/react-native-naver-map": "^1.5.6",
    "react": "18.2.0",
    "react-native": "^0.71.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/preset-env": "^7.14.0",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^3.0.0",
    "@tsconfig/react-native": "^2.0.2",
    "@types/jest": "^29.2.1",
    "@types/react": "^18.0.24",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.2.1",
    "eslint": "^8.19.0",
    "jest": "^29.2.1",
    "metro-react-native-babel-preset": "0.73.5",
    "prettier": "^2.4.1",
    "react-test-renderer": "18.2.0",
    "typescript": "4.8.4"
  },
  "jest": {
    "preset": "react-native"
  },
  "packageManager": "yarn@3.6.4"
}
```

### Relevant log output

```shell
> ERROR
Error setting property 'clusters' of RNCNaverMapView with tag #3: JSON value '{
    clusters =     (
    );
    key = "";
}' of type NSMutableDictionary cannot be converted to NSArray
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mym0404** [comment]
안녕하세요 Xcode 버전때문인지 제 프로젝트에선 sample의 iOS가 빌드되지 않아 `1.5.8`에 의심되는 부분을 수정해서 배포해두었으니 확인하시면 될 것 같습니다.

**Comment by Arthur-Noh** [comment]
@mym0404 
아이폰에서 정상적으로 기동됩니다.
수정해주셔서 감사합니다.

**Comment by mym0404** [comment]
네 이슈를 찾아주셔서 감사합니다.
