### ISSUE TITLE
[FR]: 클러스터링 클릭 이벤트

### ISSUE THREAD

**Issue by mingyeom1** [mym0404/react-native-naver-map#46]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of @mj-studio/react-native-naver-map

1.5.8

### Version of react-native

0.72.6

### What os are you seeing the problem on?

Android, iOS

### What device types are you seeing the problem on?

Simulator, Physcial Device

### What architecture types of react native are you seeing the problem on?

New Architecture(Fabric)

### Expo App

- [ ] I am using Expo

### What happened?

클러스터링 구현 시 최대 줌 레벨에서 NaverMapMarkerOverlay의 onTap 이벤트 처럼 이미지 클릭 이벤트를 받을 수 있는 방법이 있을까요?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mym0404** [comment]
아직 구현되지 않은 기능이지만 identifier를 설정한것을 기반으로 mapview의 prop으로 콜백을 노출할 수 있을것같습니다.

그런데 뭉쳐있는 클러스터의 경우 identifier merge 전략을 수립해야할것같습니다

**Comment by mingyeom1** [comment]
> 아직 구현되지 않은 기능이지만 identifier를 설정한것을 기반으로 mapview의 prop으로 콜백을 노출할 수 있을것같습니다.
> 
> 그런데 뭉쳐있는 클러스터의 경우 identifier merge 전략을 수립해야할것같습니다

그렇군요..
`identifier를 설정한것을 기반으로 mapview의 prop으로 콜백을 노출할 수 있을것같습니다.`
이 부분이 잘 이해가 되지 않는데 좀 더 자세히 설명해주실 수 있을까요?

혹시 업데이트 예정은 언제쯤 있을까요?!

**Comment by mym0404** [comment]
`onClusterMarkerTap?: (params: {markerIdentifier: string}) => void`; 같은 Prop을 만든다는 의미였습니다.

조만간 업데이트가 될 것 같습니다.

**Comment by mym0404** [comment]
`2.0.0-alpha02`의 `onTapClusterLeaf`를 사용하시면 됩니다. `2.x` 는 Fabric에서만 구동 가능합니다.

**Comment by mingyeom1** [comment]
> `2.0.0-alpha02`의 `onTapClusterLeaf`를 사용하시면 됩니다. `2.x` 는 Fabric에서만 구동 가능합니다.

감사합니다!
