### ISSUE TITLE
[BUG]: Android ref setLocationTrackingMode is not working.

### ISSUE THREAD

**Issue by Arthur-Noh** [mym0404/react-native-naver-map#54]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of @mj-studio/react-native-naver-map

1.5.9

### Version of react-native

0.74.1

### What os are you seeing the problem on?

Android

### What device types are you seeing the problem on?

Physcial Device

### What architecture types of react native are you seeing the problem on?

Old Architecture(Bridge)

### Version of device(android API, iOS OS version, etc...)

Android 34

### Expo App

- [ ] I am using Expo

### What happened?

안녕하세요.

안드로이드에서 NaverMapViewRef 의 setLocationTrackingMode 가 동작하지 않는 것 같습니다.
아이폰에서는 정상적으로 Follow, Face 모두 동작하지만 안드로이드에서는 동작하지 않습니다.

권한 문제인가 싶어 봤는데,
네이버 맵에서 기본으로 제공하는 LocationButton (isShowLocationButton) 은 안드로이드에서 정상적으로 동작합니다.

확인해주시면 감사하겠습니다.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mym0404** [comment]
저번에 동일한 리포트가 들어와서 확인해보았을때 `setLocationTrackingMode`가 안드로이드에서 정상 작동함을 확인했고 아예 그 함수 자체를 호출했을 때 내 위치 아이콘이 변경이 안된다는 뜻이신가요?

`2.0.0-alpha02`에서도 실기기에서 동일한 현상이 일어나는지 살펴보시고 만약 그렇다면 다시 말씀해주시면 감사하겠습니다.

**Comment by mym0404** [comment]
https://github.com/mym0404/react-native-naver-map/assets/33388801/434bfc16-c711-4eeb-a4f1-d54f217ee66d

**Comment by Arthur-Noh** [comment]
음.. `setLocationTrackingMode ` 수행 자체는 되지만 파란색 점 (내위치) 가 표기되지 않습니다.
Follow 했을때 내 위치가 화면상 중앙으로 이동하기를 기대하는데 동작하지 않네요.

`2.0.0-alpha02` 는 0.74.1 에서 앱 설치가 정상적으로 수행되지가 않네요.

설치할 때 android studio 에 나오는 문구들입니다.
```
e: file:///Users/arthurnoh/workspace/test-app/node_modules/@mj-studio/react-native-naver-map/android/src/main/java/com/mjstudio/reactnativenavermap/mapview/RNCNaverMapViewManager.kt:177:3 'setMapType' overrides nothing
e: file:///Users/arthurnoh/workspace/test-app/node_modules/@mj-studio/react-native-naver-map/android/src/main/java/com/mjstudio/reactnativenavermap/mapview/RNCNaverMapViewManager.kt:197:3 'setLayerGroups' overrides nothing
e: file:///Users/arthurnoh/workspace/test-app/node_modules/@mj-studio/react-native-naver-map/android/src/main/java/com/mjstudio/reactnativenavermap/mapview/RNCNaverMapViewManager.kt:233:3 'setInitialCamera' overrides nothing
e: file:///Users/arthurnoh/workspace/test-app/node_modules/@mj-studio/react-native-naver-map/android/src/main/java/com/mjstudio/reactnativenavermap/mapview/RNCNaverMapViewManager.kt:246:3 'setCamera' overrides nothing
... 비슷한 오류들 쭉 출력되며 빌드되지 않음
```
![스크린샷 2024-05-31 오전 10 48 05](https://github.com/mym0404/react-native-naver-map/assets/88483892/d699f538-d303-4667-9eef-dc62dd9cfc27)

**Comment by Arthur-Noh** [comment]
> > img-7598_gaWaQIjE.mp4
> 
> 음.. `setLocationTrackingMode ` 수행 자체는 되지만 파란색 점 (내위치) 가 표기되지 않습니다. Follow 했을때 내 위치가 화면상 중앙으로 이동하기를 기대하는데 동작하지 않네요.
> 
> `2.0.0-alpha02` 는 0.74.1 에서 앱 설치가 정상적으로 수행되지가 않네요.
> 
> 설치할 때 android studio 에 나오는 문구들입니다.
> 
> ```
> e: file:///Users/arthurnoh/workspace/test-app/node_modules/@mj-studio/react-native-naver-map/android/src/main/java/com/mjstudio/reactnativenavermap/mapview/RNCNaverMapViewManager.kt:177:3 'setMapType' overrides nothing
> e: file:///Users/arthurnoh/workspace/test-app/node_modules/@mj-studio/react-native-naver-map/android/src/main/java/com/mjstudio/reactnativenavermap/mapview/RNCNaverMapViewManager.kt:197:3 'setLayerGroups' overrides nothing
> e: file:///Users/arthurnoh/workspace/test-app/node_modules/@mj-studio/react-native-naver-map/android/src/main/java/com/mjstudio/reactnativenavermap/mapview/RNCNaverMapViewManager.kt:233:3 'setInitialCamera' overrides nothing
> e: file:///Users/arthurnoh/workspace/test-app/node_modules/@mj-studio/react-native-naver-map/android/src/main/java/com/mjstudio/reactnativenavermap/mapview/RNCNaverMapViewManager.kt:246:3 'setCamera' overrides nothing
> ... 비슷한 오류들 쭉 출력되며 빌드되지 않음
> ```
> 
> ![스크린샷 2024-05-31 오전 10 48 05](https://private-user-images.githubusercontent.com/88483892/335420037-d699f538-d303-4667-9eef-dc62dd9cfc27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0NjI2NDEsIm5iZiI6MTcxNzQ2MjM0MSwicGF0aCI6Ii84ODQ4Mzg5Mi8zMzU0MjAwMzctZDY5OWY1MzgtZDMwMy00NjY3LTllZWYtZGM2MmRkOWNmYzI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDAwNTIyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2ZWZhNzFhMmY4ZjMwZDkwZGMwYzdmODNmNDliMTk3ZTgyYzg5MzBhNmY1YjFhNWM1NDk3NDc2NDU0OWNlNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8L5EcX0o6JvLd-W9F8JCdcX8BSqwf3G_iqOiRVfQF04)

Old Architecture(Bridge)형식에서 빌드 했기 때문에 생성된 문제네요!
확인 해보고 다시 코멘트 남기겠습니다.

**Comment by jb9229** [comment]
@mym0404 
Old Architecture 이슈 인데, 이슈 해결 계획이 없으신가요?

**Comment by mym0404** [comment]
old arch만의 문제라고 판단하신 이유가 있을까요? 어떤 부분이 문제인지 정확히 파악되지 않은 이슈같습니다.

**Comment by jb9229** [comment]
안드로이드에서 내 위치 표시 안되는 이슈가, 아래와 같이 재현이 됩니다.

이슈 재현:
- newArchEnabled: false 빌드 시, 내 위치 표시 및 setLocationTrackingMode 정상 작동함
- newArchEnabled: true 빌드 시, 내 위치 표시 안됨 및 setLocationTrackingMode 동작 안함

추가 정보:
- expo 사용

**Comment by jb9229** [comment]
1.5.9 버전 입니다.

보니깐, isShowLocationButton={false}로 해서 그러네요.
저는  isShowLocationButton={false}로 하고, 버튼을 따로 만들어 setLocationTrackingMode변경만 했었는데.
- setupLocationSource를 setIsShowLocationbutton에서 호출하기 때문에 isShowLocationButton={trure}로 설정해야 하겠네요!?
![image](https://github.com/user-attachments/assets/a8d1d5d1-6ed0-4c87-ad66-6a6c1d91e53f)

**Comment by mym0404** [comment]
네 지금 구조상은 그런것같습니다. 제보 감사합니다.
