### ISSUE TITLE
[BUG]: requireNativeComponent: "RNCNaverMapView" was not found in the UIManager.

### ISSUE THREAD

**Issue by hangyeol-shin** [mym0404/react-native-naver-map#61]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of @mj-studio/react-native-naver-map

1.5.9

### Version of react-native

0.68.2

### What os are you seeing the problem on?

iOS

### What device types are you seeing the problem on?

Simulator

### What architecture types of react native are you seeing the problem on?

Old Architecture(Bridge)

### Expo App

- [ ] I am using Expo

### What happened?

기본 설정을 완료한 후, 아래와 같이 `NaverMapView`을 렌더링 하면, 
```
import React from 'react';
import {View, StyleSheet} from 'react-native';
import {NaverMapView} from '@mj-studio/react-native-naver-map';

const RNMapScreen: React.FC = () => {
  return (
    <View style={styles.container}>
      <NaverMapView />
    </View>
  );
};
```

아래와 같은 에러 메시지가 발생하면서 컴포넌트가 그려지지 않고 있습니다
```
nvariant Violation: requireNativeComponent: "RNCNaverMapView" was not found in the UIManager.

This error is located at:
    in RNCNaverMapView (at NaverMapView.tsx:864)
    in Unknown (at RNMapScreen/index.tsx:8)
    in RCTView (at View.js:32)
    in View (at RNMapScreen/index.tsx:7)
    in RNMapScreen (at App.tsx:56)
    in RCTSafeAreaView (at SafeAreaView.js:51)
    in SafeAreaView (at App.tsx:52)
    in App (at renderApplication.js:50)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:92)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:43)
```

RN에 익숙치 않아서, 혹시 추가로 설정해야하거나 살펴봐야하는 부분이 있다면 알려주시면 감사하겠습니다!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by junleejaehyuk** [comment]
경험상 react-native --reset-cache 후 재빌드를 시도해보시거나 메트로 강제종료 앱삭제 후 다시 빌드한번 해보세요~

**Comment by mym0404** [comment]
UIManager에 naver map 컴포넌트가 등록되지 않아서 일어나는 현상입니다. 라이브러리 설치 후 pod install 및 프로젝트를 다시 빌드하는 과정이 필요합니다.

**Comment by hangyeol-shin** [comment]
@mym0404 말씀해주신대로, 설치 후 재빌드 및 다양한 초기화 방법 이후에 다시 실행해봐도 동일한 이슈가 발생합니다 ㅠㅠ
현재 사용하고 있는 RN이 0.68 로, 비교적 구버전이긴 한데, 혹시 이게 문제가 될 수 있을까요??

**Comment by mym0404** [comment]
네 그럴것같습니다. RN 0.68로는 빌드해보지 않아서 잘 모르겠습니다.

**Comment by leahincom** [comment]
@hangyeol-shin Expo go 에서는 사용하지 못하고, eas build 로는 접근 가능한 것 같아요.
https://github.com/mym0404/react-native-naver-map?tab=readme-ov-file#3-expo-support

RN >= 0.74 사용하고 있고, go 환경에서는 저도 접근 못 하고 있어요

**Comment by mym0404** [comment]
Expo go는 미리 포함된 native library들만 가능하기 때문에 이 라이브러리 사용이 불가능합니다. 하지만 Expo의 Development Build를 이용하면 가능하고 그걸 위한 config plugin도 이 패키지에 자동으로 내장되어 있으니 어렵지않게 Expo 환경에서도 사용 가능합니다.
