### ISSUE TITLE
[BUG]: 2 버전때의 android build 이슈

### ISSUE THREAD

**Issue by junleejaehyuk** [mym0404/react-native-naver-map#63]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of @mj-studio/react-native-naver-map

v2.0.0-rc.1

### Version of react-native

0.73.6

### What os are you seeing the problem on?

Android

### What device types are you seeing the problem on?

Physcial Device

### What architecture types of react native are you seeing the problem on?

0.73.6

### Expo App

- [ ] I am using Expo

### What happened?

안녕하세요. 
패키지를 만들고 관리하시는데 감사드립니다.

1.5.9 버전을 잘 사용하고 있었습니다.
클러스터의 클릭 이벤트의 가능을 사용하고자  v2.0.0-rc.1 및 v2.0.0-alpha.2 으로 버전 업데이트 했지만

```
Execution failed for task ':mj-studio_react-native-naver-map:compileDebugKotlin'.
> A failure occurred while executing    org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
```

해당에러가 제출이됩니다

제 build.gradle 은 아래와같습니다.

```
buildscript {
    ext {
        buildToolsVersion = "34.0.0"
        minSdkVersion = 21
        compileSdkVersion = 34
        targetSdkVersion = 34
        ndkVersion = "25.1.8937393"
        kotlinVersion = "1.8.0"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin")
	classpath("com.google.gms:google-services:4.3.15")
    }
}

allprojects {
    repositories {
        maven {
            url "https://repository.map.naver.com/archive/maven"
        }
    }
}

apply plugin: "com.facebook.react.rootproject

```
fabric 이슈일수도 있다는 생각이 드는데

newArchEnabled=true로 설정시 다른 타사라이브러리들 오류들이 발생해서,

fabric 아닐때도 해당 기능을 사용할수 있는 해결책이나 업데이트가 있나요?

감사합니다.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mym0404** [comment]
2.x.x 부턴 New Architecture에서만 구동 가능합니다.
