### ISSUE TITLE
[BUG]: 터치가 끝난 뒤, 카메라 좌표를 구할 방법이 있을까요?

### ISSUE THREAD

**Issue by yctae** [mym0404/react-native-naver-map#65]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of @mj-studio/react-native-naver-map

1.5.9

### Version of react-native

0.74.1

### What os are you seeing the problem on?

Android, iOS

### What device types are you seeing the problem on?

Physcial Device

### What architecture types of react native are you seeing the problem on?

New Architecture(Fabric)

### Expo App

- [X] I am using Expo

### What happened?

onCameraChanged와 같이 실시간 좌표 추적이 아닌,
onTouchEnd 이벤트 시에 카메라 좌표를 알 수 있는지 알고 싶습니다.
react-native-maps의 onRegionChangeComplete 와 같은 이벤트 입니다.

직접 onTouchStart와 onTouchEnd 이벤트를 통해 만들어 보려 했지만

IOS에서는 onTouchStart와 onTouchEnd 등과 같은 터치 관련 이벤트가 정상 동작하는데
안드로이드에서는 터치 관련 이벤트가 정상 동작하지 않습니다.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mym0404** [comment]
[onTapMap](https://mym0404.github.io/react-native-naver-map/interfaces/NaverMapViewProps.html#onTapMap) prop을 사용해보시길 바랍니다.
