### ISSUE TITLE
[BUG]:  드래그로 지도 이동 후 center 위도, 경도 정보 확인할 수 있을까요?

### ISSUE THREAD

**Issue by anes118** [mym0404/react-native-naver-map#69]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of @mj-studio/react-native-naver-map

"@mj-studio/react-native-naver-map": "1.5.9",

### Version of react-native

"react-native": "0.72.12",

### What os are you seeing the problem on?

Android

### What device types are you seeing the problem on?

Physcial Device

### What architecture types of react native are you seeing the problem on?

Old Architecture(Bridge)

### Expo App

- [ ] I am using Expo

### What happened?

A bug happened!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mym0404** [comment]
[onTapMap](https://mym0404.github.io/react-native-naver-map/interfaces/NaverMapViewProps.html#onTapMap) prop을 사용해보시길 바랍니다.
