### ISSUE TITLE
[FR]: 카메라 완료, 취소 이벤트

### ISSUE THREAD

**Issue by anes118** [mym0404/react-native-naver-map#70]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of @mj-studio/react-native-naver-map

"@mj-studio/react-native-naver-map": "1.5.9"

### Version of react-native

"react-native": "0.72.12",

### What os are you seeing the problem on?

Android

### What device types are you seeing the problem on?

Physcial Device

### What architecture types of react native are you seeing the problem on?

Old Architecture(Bridge)

### Expo App

- [ ] I am using Expo

### What happened?

naverMap.addOnCameraIdleListener(() -> {
    Toast.makeText(context, "카메라 움직임 종료", Toast.LENGTH_SHORT).show();
});
위 기능은 어디서 확인이 가능할까요?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mym0404** [comment]
무슨 말씀이신지 모르겠습니다. 해당 기능에 대한 공식문서 링크나 더 자세한 설명을 적어주세요.

**Comment by anes118** [comment]
https://navermaps.github.io/android-map-sdk/guide-ko/3-2.html

위 링크 내용 중 

카메라 대기 이벤트
카메라의 움직임이 끝나 대기 상태가 되면 카메라 대기 이벤트가 발생합니다. [NaverMap.addOnCameraIdleListener()](https://navermaps.github.io/android-map-sdk/reference/com/naver/maps/map/NaverMap.html#addOnCameraIdleListener%28com.naver.maps.map.NaverMap.OnCameraIdleListener%29) 메서드로 [OnCameraIdleListener](https://navermaps.github.io/android-map-sdk/reference/com/naver/maps/map/NaverMap.OnCameraIdleListener.html)를 등록하면 카메라 대기 이벤트를 받을 수 있습니다. 카메라가 대기 상태가 되면 [onCameraIdle()](https://navermaps.github.io/android-map-sdk/reference/com/naver/maps/map/NaverMap.OnCameraChangeListener.html#onCameraChange%28int%2Cboolean%29) 콜백 메서드가 호출됩니다.

카메라는 다음과 같은 시점에 대기 상태가 된 것으로 간주되어 이벤트가 발생합니다.

카메라가 애니메이션 없이 움직일 때. 단, 사용자가 제스처로 지도를 움직이는 경우 제스처가 완전히 끝날 때까지([ACTION_UP](https://developer.android.com/reference/android/view/MotionEvent#ACTION_UP)이 발생할 때까지)는 연속적인 이동으로 간주되어 이벤트가 발생하지 않습니다.
카메라 애니메이션이 완료될 때. 단, 카메라 애니메이션이 진행 중일 때 새로운 애니메이션이 발생하거나, 기존 카메라 이동의 finishCallback() 또는 cancelCallback()으로 지정된 콜백 내에서 카메라 이동이 일어날 경우 연속적인 이동으로 간주되어 이벤트가 발생하지 않습니다.
NaverMap.cancelTransitions()가 호출되어 카메라 애니메이션이 명시적으로 취소될 때.
다음은 카메라가 대기 상태가 되면 토스트를 표시하는 예제입니다.

위 내용입니다

**Comment by mym0404** [comment]
이동 이벤트말고 취소, 완료 콜백은 구현되어 있지 않습니다.
