### ISSUE TITLE
[FR]: onLocationChange 문의

### ISSUE THREAD

**Issue by anes118** [mym0404/react-native-naver-map#71]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

https://navermaps.github.io/android-map-sdk/guide-ko/4-2.html
위 링크의 
위치 변경 이벤트
[addOnLocationChangeListener()](https://navermaps.github.io/android-map-sdk/reference/com/naver/maps/map/NaverMap.html#addOnLocationChangeListener%28com.naver.maps.map.NaverMap.OnLocationChangeListener%29) 메서드로 [OnLocationChangeListener](https://navermaps.github.io/android-map-sdk/reference/com/naver/maps/map/NaverMap.OnLocationChangeListener.html)를 등록하면 위치 변경에 대한 이벤트를 받을 수 있습니다. 위치 추적 모드가 활성화되고 사용자의 위치가 변경되면 [onLocationChange()](https://navermaps.github.io/android-map-sdk/reference/com/naver/maps/map/NaverMap.OnLocationChangeListener.html#onLocationChange%28android.location.Location%29) 콜백 메서드가 호출되며, 파라미터로 사용자의 위치가 전달됩니다.

위 내용입니다

### Describe the solution

어떻게 처리하면 되는지 문의드립니다.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mym0404** [comment]
아직 저 함수는 포팅되어있지 않습니다. 하지만 사용자의 위치는 지도에서말고 Location 기능을 제공해주는 Library들을 이용해 얻어올 수도 있습니다.

**Comment by mym0404** [comment]
This issue is moved to #74
